[project]
name = "Diffusion_Module"
version = "0.1.0"
description = "Acoustics Simulation using the Diffusion Equation"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]
